### ISSUE TITLE
Publishing a collection of datasets

### ISSUE THREAD

**Issue by benbovy** [xarray-contrib/xpublish#23]
It would be great if we could publish multiple datasets on the same server.

I'm thinking of something like this:

```python
xpublish.serve(
    {'ds1': xarray.Dataset(...), 'ds2': xarray.Dataset(...)},
    host="127.0.0.1",
    port=9000
)
```

or 

```python
# will launch the server
ds1.rest.serve(host="127.0.0.1", port=9000, name="ds1")

# same host/port -> will reuse the server
ds2.rest.serve(host="127.0.0.1", port=9000, name="ds2")
```

Would there be any technical challenge in supporting this?

This will certainly break the current API end points, unless both cases (single dataset vs collection of datasets) are supported (perhaps not on the same running server).

For the case of multiple datasets, all the current end points could for example have the prefix `/datasets/<name>/`. Some additional end points may be useful for listing the datasets in the collection.

**Comment by jhamman** [comment]
Yes, this is possible today. @lsetiawan has done this and I’m hoping he can share an example.

**Comment by lsetiawan** [comment]
@benbovy Here’s an example that I’ve created with that similar thought: https://api-dev.ooica.net/ I you click link, that will lead to the individual xpublished dataset. The logistic incorporating that straight into xpublish library.. not sure. Have to brainstorm that with @jhamman

**Comment by benbovy** [comment]
@lsetiawan looks nice! How do you reuse xpublish in that example? Do you run separate instances of the FastAPI app for each dataset (e.g., each on a different port)?

**Comment by lsetiawan** [comment]
@benbovy My current approach is to mount each dataset on their own endpoint. `xpublish` allows the user to access the FastAPI app object.
```
app.mount(
                f"/{dataset_id}", ds.app
)
```

I want to get to being able to have each dataset in a different port and be published independently from the central API. Since right now reading in 135 large datasets takes up a huge amount of memory, and it's not distributed... My plan is to be able to publish each dataset in its own pod in a kubernetes cluster for example. Any thoughts on this would be awesome!

**Comment by benbovy** [comment]
Thanks for sharing your approach @lsetiawan ! I need to have a deeper look at the FastAPI docs. TBH, I don't have much experience in developing/deploying APIs.

I guess it makes sense to have independent apps running for each dataset for the reasons that you mention.

That said, from what I see in [mounting sub-applications](https://fastapi.tiangolo.com/advanced/sub-applications-proxy/#mount-the-sub-application), docs are created for each published dataset. That's not ideal, since in this case each sub-application exposes the exact same API. That's not a big deal, though. Maybe FastAPI is flexible enough to configure this properly?

I think that, for convenience, it would be worth implementing this approach in xpublish, e.g., with a top level function:

```
main_app = xpublish.serve(
    xr_datasets_dict,
    host="127.0.0.1",
    port=9000,
    openapi_prefix="/datasets",
)
```

`main_app` would have the following endpoints:

- `/datasets`: list of all datasets (their name)
- `datasets/{name}`: sub-app mount point
- `/docs`: ideally serves the documentation for the whole API, including single dataset endpoints.

**Comment by jhamman** [comment]
@benbovy - I like this idea and would love to see someone prototype such a thing. Contributions welcome!

**Comment by benbovy** [comment]
I added a prototype in #25 that allows reusing the same routes for serving a collection of dataset either as a single FastAPI application or as a set of independent sub-applications.

I think both alternatives have pros and cons. For @lsetiawan's case one sub-application per dataset makes sense. For cases where the datasets are already distributed, I'm not sure if having one pod per dataset is really needed (I guess a Dask cluster and a Zarr distributed storage would take care of all the distributed aspects?).

Having one application with `/datasets/{dataset_id}/<something>` routes has the advantage of providing a single openapi spec and allows serving a dynamic collection of xarray Datasets (i.e., add or remove datasets without the need to restart the application).
