### ISSUE TITLE
Move this project to a new GitHub organization?

### ISSUE THREAD

**Issue by jhamman** [xarray-contrib/xpublish#28]
Recently, @lsetiawan and @benbovy have been making contributions to this repository. Would now be a good time to move the repository to a GitHub organization. I think [xarray-contrib](https://github.com/xarray-contrib) is a logical place but Pangeo would also be fine by me.

**Comment by benbovy** [comment]
+1 for moving it to xarray-contrib.

**Comment by andersy005** [comment]
👍 for moving it under xarray-contrib

**Comment by jhamman** [comment]
Okay! I’m going to do this later today.

**Comment by jhamman** [comment]
Done!
