### ISSUE TITLE
release 0.0.3?

### ISSUE THREAD

**Issue by jhamman** [xarray-contrib/xpublish#32]
We've just merged some significant features and refactors. Is now a good time to make the 0.0.3 release?

cc @benbovy

**Comment by benbovy** [comment]
I'd like to make a few tweaks / fixes in the docs (I think there are still some places where the repo url needs to be updated `jhamman` -> `xarray-contrib`, and we could use https://github.com/keewis/sphinx-autosummary-accessors for documenting the `rest` accessor).

Also I'd like to implement serving a collection of datasets, which should be pretty straightforward.

But we could release 0.0.4 shortly after a 0.0.3 release, I don't have  any problem with that. Or maybe I will be time for a 0.1.0 release?

**Comment by jhamman** [comment]
@benbovy - any problems with me proceeding with a 0.1 release now?

**Comment by benbovy** [comment]
No problem :-) !

**Comment by jhamman** [comment]
closed via 7570d40
